
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 23298
 */
public class formCarro extends javax.swing.JFrame {
    Carro carro = new Carro();
    /**
     * Creates new form formCarro
     */
    public formCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textcarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textano = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textplaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textdono = new javax.swing.JTextField();
        buttoncadastro = new javax.swing.JButton();
        buttomexibir = new javax.swing.JButton();
        buttomsair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textkm = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carro");

        jLabel2.setText("Nome do carro:");

        textcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcarroActionPerformed(evt);
            }
        });

        jLabel3.setText("Ano de fabricação:");

        jLabel4.setText("Placa do carro:");

        jLabel5.setText("Dono do carro");

        buttoncadastro.setText("Cadastrar");
        buttoncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastroActionPerformed(evt);
            }
        });

        buttomexibir.setText("Exibir");
        buttomexibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomexibirActionPerformed(evt);
            }
        });

        buttomsair.setText("Sair");

        jLabel7.setText("KM rodado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttomsair))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textcarro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttoncadastro)
                        .addGap(18, 18, 18)
                        .addComponent(buttomexibir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textano)
                            .addComponent(textplaca)
                            .addComponent(textdono)
                            .addComponent(textkm))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textcarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textdono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(textkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttoncadastro)
                    .addComponent(buttomexibir))
                .addGap(45, 45, 45)
                .addComponent(buttomsair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcarroActionPerformed

    private void buttoncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastroActionPerformed
        carro.carro=this.textcarro.getText();
        carro.ano=Integer.parseInt(this.textano.getText());
        carro.placa=Integer.parseInt(this.textplaca.getText());
        carro.dono=this.textdono.getText();
        carro.km=Double.parseDouble(this.textkm.getText());
        JOptionPane.showMessageDialog(null,"Dados Cadastrados");
        this.textcarro.setText(" ");
        this.textano.setText(" ");
        this.textplaca.setText(" ");
        this.textdono.setText(" ");
        this.textkm.setText(" ");
    }//GEN-LAST:event_buttoncadastroActionPerformed

    private void buttomexibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomexibirActionPerformed
        this.textcarro.setText(""+carro.carro);
        this.textano.setText(""+carro.ano);
        this.textkm.setText(""+carro.km);
        this.textdono.setText(""+carro.dono);
        this.textplaca.setText(""+carro.placa)  ;      
    }//GEN-LAST:event_buttomexibirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomexibir;
    private javax.swing.JButton buttomsair;
    private javax.swing.JButton buttoncadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textano;
    private javax.swing.JTextField textcarro;
    private javax.swing.JTextField textdono;
    private javax.swing.JTextField textkm;
    private javax.swing.JTextField textplaca;
    // End of variables declaration//GEN-END:variables
}
